### ISSUE TITLE
I wish to contribute to mljs

### ISSUE THREAD

**Issue by keonkim** [mljs/ml#14]
Is there contribution guide lines?

**Comment by keonkim** [comment]
I want to start with decision tree algorithm is it ok?

**Comment by targos** [comment]
Hello and thank you for your interest in our project :) You are very welcome to contribute.
We currently haven't defined precise guidelines. The project is quite young and has not a lot of different collaborators.

If you want to start working on a new algorithm, I can setup an empty repository for you.
One of the goals in this organization is to have many small librairies (that can depend on each other), focused on a specific task / algorithm and that we publish on npm.
I assume that you are interested in [decision tree learning](https://en.wikipedia.org/wiki/Decision_tree_learning), which is a pretty general category. Do you have one specific algorithm in mind ?

**Comment by keonkim** [comment]
I meant CART algorithm.
I found no good library that does that in pure javascript.
I will benchmark python scikit-learn's tree algorithm.

**Comment by targos** [comment]
@keonkim sorry for the delay, I hope you are still interested in implementing this algorithm!
If so, I created the repository for you with a few boilerplate files here: https://github.com/mljs/decision-tree-cart

In the organization, we are trying to collaborate on all the projects and to have proper code review using the [GitHub flow](https://guides.github.com/introduction/flow/). I suggest you start working on a new branch and create a pull request against `master` so that we can discuss about the work.

Feel free to ask us any question.

**Comment by keonkim** [comment]
thanks! I'll get to work soon
